[ Feature ] QR code padding
kenyoni-software/godot-addons pull request #3
Opened 2023-09-10 16:30 UTC by rylydou

Amazing work on this extension! I've been trying to find a qr code plugin that actually works for a while now. Before this I tried using a modified version of [this addon](https://github.com/Greaby/godot-qrcode-generator/tree/godot-4) for the a little bit but it was super buggy.

This PR adds padding support for the qr code texture. The padding is based on `module_px_size`. The color uses the `light_module_color`.

Here's what a padding size of 1 looks like:
![image](https://github.com/kenyoni-software/godot-addons/assets/58660466/4bcee223-b65e-421e-9c84-1e4ced7d41fc)

I can't figure out how to get the inspector to only allow positive numbers and zero. I tried `editor_hint: '0,1,or_greater'` but it doesn't seam to work.

2023-09-10 16:31 UTC, rylydou commented
Oops turns out my commits aren't signed I need to fix that.

2023-09-10 17:03 UTC, IceflowRE commented
Thank you for the suggestion!
The correct term you are looking for is `quiet_zone`, by default it should be `4` (Chapter 6.3.8)

If you are are ready, that i can review this PR, just ping me.

2023-09-10 17:04 UTC, IceflowRE commented
If possible could you remove the spaces inside the brackets in the commit message? thanks.

2023-09-10 23:12 UTC, rylydou commented
I renamed the properties and I figured out how to block negative values from being entered. The default is still 1 but there is a tool tip explaining that 4 is recommend by the standard. (Feel free to change it to 4 if you want)

I'm not sure if I can rename the older commits but when you merge this PR you I think it will get squashed. (I'm still a git noob apparently)

2023-09-11 12:48 UTC, IceflowRE requested changes

2023-09-11 12:48 UTC, IceflowRE commented on README.md
> +  Use that many modules for the quite zone. A value of 4 is recommend.
```suggestion
- `quiet_zone_size: int`  
  Use that many modules for the quiet zone. A value of 4 is recommended.
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code.gd
> +    quite_zone_size = max(0, quite_zone_size)
```suggestion
func generate_image(module_px_size: int = 1, light_module_color: Color = Color.WHITE, dark_module_color: Color = Color.BLACK, quiet_zone_size: int = 4) -> Image:
    module_px_size = max(1, module_px_size)
    quiet_zone_size = max(0, quiet_zone_size)
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code.gd
> +    image.fill(light_module_color)
```suggestion
    var image_size: int = (module_count + 2 * quiet_zone_size) * module_px_size
    var image: Image = Image.create(image_size, image_size, false, Image.FORMAT_RGB8)
    image.fill(light_module_color)
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code.gd
> +            match qr_code[x + y*module_count]:
```suggestion
            match qr_code[x + y * module_count]:
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code.gd
> +                    image.set_pixel((x + quite_zone_size)*module_px_size + offset_x, (y + quite_zone_size)*module_px_size + offset_y, color)
```suggestion
                    image.set_pixel((x + quiet_zone_size) * module_px_size + offset_x, (y + quiet_zone_size) * module_px_size + offset_y, color)
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code_rect.gd
> +    set = set_quite_zone_size
```suggestion
var quiet_zone_size: int = 4:
    set = set_quiet_zone_size
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code_rect.gd
> +    self._update_qr()
```suggestion
func set_quiet_zone_size(new_quiet_zone_size: int) -> void:
    quiet_zone_size = max(0, new_quiet_zone_size)
    self._update_qr()
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code_rect.gd
> +            "name": "quite_zone_size",
```suggestion
            "name": "quiet_zone_size",
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code_rect.gd
> +            "hint_string": "1,1,or_greater",
```suggestion
            "hint_string": "0,1,or_greater",
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code_rect.gd
> +    return property in ["auto_version", "auto_mask_pattern", "light_module_color", "dark_module_color", "auto_module_px_size", "quite_zone_size"]
```suggestion
    return property in ["auto_version", "auto_mask_pattern", "light_module_color", "dark_module_color", "auto_module_px_size", "quiet_zone_size"]
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code_rect.gd
> +            return 1
```suggestion
        "quiet_zone_size":
            return 4
```

2023-09-11 12:48 UTC, IceflowRE commented on addons/qr_code/qr_code_rect.gd
> +    self.texture = ImageTexture.create_from_image(self._qr.generate_image(self.module_px_size, self.light_module_color, self.dark_module_color, self.quite_zone_size))
```suggestion
    self.texture = ImageTexture.create_from_image(self._qr.generate_image(self.module_px_size, self.light_module_color, self.dark_module_color, self.quiet_zone_size))
```

2023-09-11 12:54 UTC, IceflowRE commented
> I'm not sure if I can rename the older commits but when you merge this PR you I think it will get squashed. (I'm still a git noob apparently)

Yes sure, just edit them, or make your changes, squash yourself, rename the squashed commit and force push to your branch.

2023-09-11 15:37 UTC, merged

2023-09-11 15:37 UTC, IceflowRE commented
Thanks for the contribution! It is a nice addition.